language: node_js
node_js:
  - "6"
script:
  - yarn build
  - yarn test
  - yarn flow
  - yarn lint

  # Run tests for built version
  - cp -r src/__tests__ dist/__tests__
  - yarn test --testRegex dist/__tests__/.*(\\.test.js)$
